"""Ghidra emitters: symbol application and CFG-edge recovery.

Two distinct jobs, and the difference matters:

* **Symbols** (`symbols.py`) name what Ghidra already found.
* **CFG edges** (here) tell Ghidra about control flow it *could not find*, because the
  engine dispatches through register-indirect jumps. Patching the bytes to make the
  jump direct also works, but it destroys the original and (measured) buys almost
  nothing. Injecting the edges as references keeps the binary pristine and is
  reversible, so it is the method to prefer.

Ghidra cannot be told "there is an edge" in the abstract: an edge has to be attached
to a decoded instruction. So the generated script does three things per edge:

  1. force disassembly at the target (an edge into undecoded bytes is meaningless),
  2. create a `COMPUTED_JUMP` reference from the branch site to the target,
  3. optionally start a function at targets that nothing else reaches.

Step 3 is what actually makes the decompiler treat the target as a successor; step 2
alone often just annotates. Both are emitted so the caller can measure the effect.
"""

from __future__ import annotations

from typing import Iterable

from .model import Edge


def edges_to_rows(edges: Iterable[Edge]) -> list[tuple[int, int, str]]:
    """(site_va, target_va, kind) rows, absolute addresses."""
    rows = []
    for e in edges:
        rows.append((e.site, e.target, e.kind))
    return rows


def emit_cfg_edges_java(edge_rows: list[tuple[int, int, str]], image_base: int,
                        make_functions: bool = True,
                        comment: str = "qvm-tool: recovered indirect branch") -> str:
    """A Ghidra Java postscript that injects recovered CFG edges.

    `edge_rows` are (site RVA, target RVA, kind) -- RVAs, converted here so the
    caller does not have to think about the image base.
    """
    entries = "\n".join(
        "        new long[] {{ {site:#x}L, {tgt:#x}L }},".format(
            site=image_base + site, tgt=image_base + tgt)
        for site, tgt, _kind in edge_rows
    )
    return f'''// Auto-generated by qvm-tool -- injects CFG edges Ghidra could not find.
//
// The QVM/TVM engine dispatches through register-indirect jumps, so a recursive
// descent disassembler sees `jmp rax` and stops. qvm-tool recovers the real targets
// statically (MBA folding + backward slicing) and dynamically (emulation), and this
// script feeds them back as references so the decompiler can follow them.
//
// Unlike byte patching this leaves the binary untouched.
//
// Usage:
//   analyzeHeadless <proj> <name> -process <program> \\
//       -scriptPath <this dir> -postScript InjectQvmEdges.java
//
// @category ACE.QVM

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.symbol.RefType;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.SourceType;

public class InjectQvmEdges extends GhidraScript {{

    private static final long[][] EDGES = {{
{entries}
    }};

    @Override
    protected void run() throws Exception {{
        boolean makeFunctions = {str(make_functions).lower()};
        int added = 0, disassembled = 0, created = 0, failed = 0;

        // `RefType.COMPUTED_JUMP` is inherited from FlowType, so it compiles as a
        // FlowType; ReferenceManager wants a RefType. The object genuinely is a
        // RefType at runtime, so the downcast is both safe and necessary.
        RefType computedJump = (RefType) RefType.COMPUTED_JUMP;

        for (long[] e : EDGES) {{
            if (monitor.isCancelled()) {{
                break;
            }}
            Address site = toAddr(e[0]);
            Address tgt = toAddr(e[1]);
            try {{
                // An edge into undecoded bytes is meaningless: decode the target first.
                if (getInstructionAt(tgt) == null) {{
                    if (disassemble(tgt)) {{
                        disassembled++;
                    }}
                }}
                if (makeFunctions && getFunctionAt(tgt) == null
                        && getInstructionAt(tgt) != null) {{
                    if (createFunction(tgt, null) != null) {{
                        created++;
                    }}
                }}
                Reference r = currentProgram.getReferenceManager().addMemoryReference(
                        site, tgt, computedJump, SourceType.USER_DEFINED, 0);
                if (r != null) {{
                    added++;
                    setPreComment(site, "{comment} -> " + tgt);
                }} else {{
                    failed++;
                }}
            }} catch (Exception ex) {{
                failed++;
            }}
        }}
        println("InjectQvmEdges: edges=" + EDGES.length + " refs_added=" + added
                + " newly_disassembled=" + disassembled + " functions_created=" + created
                + " failed=" + failed);
    }}
}}
'''


def emit_cfg_edges_idc(edge_rows: list[tuple[int, int, str]], image_base: int) -> str:
    """IDA equivalent: force code at the target and add a flow cross-reference."""
    lines = ["// Auto-generated by qvm-tool -- inject recovered QVM/TVM CFG edges",
             "#include <idc.idc>", "", "static main() {", "  auto i, added;",
             "  added = 0;",
             "  auto edges = object();"]
    body = []
    for i, (site, tgt, _kind) in enumerate(edge_rows):
        body.append(f'  setattr(edges, "s{i}", 0x{image_base + site:X});')
        body.append(f'  setattr(edges, "t{i}", 0x{image_base + tgt:X});')
    lines.extend(body)
    lines.append(f"  for (i = 0; i < {len(edge_rows)}; i = i + 1) {{")
    lines.append('    auto s, t;')
    lines.append('    s = getattr(edges, sprintf("s%d", i));')
    lines.append('    t = getattr(edges, sprintf("t%d", i));')
    lines.append('    if (isUnknown(get_flags(t))) { auto_wait(); }')
    lines.append('    add_cref(s, t, fl_JN);')
    lines.append('    add_func(t, BADADDR);')
    lines.append('    added = added + 1;')
    lines.append('  }')
    lines.append('  msg(sprintf("qvm-tool: injected %d edges\\n", added));')
    lines.append("}")
    return "\n".join(lines) + "\n"
