"""Symbol model and emitters.

"Symbol decryption" for this family means recovering the symbol information the
vendor removed or hid, not decrypting a ciphertext:

  * the export table may carry unnamed ordinals, and
  * the authoritative function map lives in a *relocated* Exception directory that
    most tools never read (they read the decoy `.pdata` section instead), and
  * every virtualised function leaves a thin native stub whose real callee is only
    visible once you decode the stub -- that mapping is what turns an anonymous
    call into a named edge.

Emitters produce JSON (machine-readable), TSV (diffable), a Ghidra postscript, and
an IDA idc script so the recovered names can be applied in the analyst's tool.
"""

from __future__ import annotations

import json
from typing import Iterable

from .model import Edge, Function, Verdict
from .pe import PEMap


def build_symbols(pm: PEMap, funcs: list[Function], edges: list[Edge],
                  verdict: Verdict, stubs: list[tuple[int, Edge]]) -> list[dict]:
    syms: list[dict] = []
    vm = verdict.vm_section or ".qvm0"
    vm_range = verdict.vm_range or (0, 0)

    for name, ordinal, rva in pm.exports():
        detail = f"ordinal {ordinal}"
        if name.startswith("ord"):
            detail += " (UNNAMED in export table)"
        syms.append({"address": rva, "name": f"ace_{name}", "kind": "export",
                     "detail": detail})

    for f in funcs:
        if f.section == vm:
            syms.append({"address": f.begin, "name": f"qvm_func_{f.begin:08X}",
                         "kind": "function",
                         "detail": f"size={f.size} unwind=0x{f.unwind:X}"})
        else:
            syms.append({"address": f.begin, "name": f"sub_{f.begin:08X}",
                         "kind": "function", "detail": f"size={f.size}"})

    for caller, e in stubs:
        syms.append({"address": caller, "name": f"qvm_stub_{caller:08X}",
                     "kind": "vm_stub",
                     "detail": f"{e.kind} -> {vm} 0x{e.target:08X} "
                               f"(virtualised body; the stub is the whole function)"})

    for target, count in _cluster_counts(edges).items():
        syms.append({"address": target,
                     "name": f"qvm_entry_{target:08X}",
                     "kind": "vm_entry",
                     "detail": f"{count} native caller(s); "
                               f"{'shared' if count > 1 else 'single-use'} entry"})

    return sorted(syms, key=lambda s: (s["address"], s["kind"]))


def _cluster_counts(edges: Iterable[Edge]) -> dict[int, int]:
    counts: dict[int, int] = {}
    for e in edges:
        counts[e.target] = counts.get(e.target, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))


# ------------------------------------------------------------------ emitters

def to_json(symbols: list[dict], meta: dict | None = None) -> str:
    return json.dumps({"meta": meta or {}, "symbols": symbols},
                      indent=2, sort_keys=False)


def to_tsv(symbols: list[dict]) -> str:
    lines = ["address\tname\tkind\tdetail"]
    for s in symbols:
        lines.append(f"{s['address']:#010x}\t{s['name']}\t{s['kind']}\t{s['detail']}")
    return "\n".join(lines) + "\n"


def to_ghidra_script(symbols: list[dict], image_base: int) -> str:
    """A Ghidra postscript that creates labels and comments at recovered addresses."""
    rows = "\n".join(
        "    ({addr}, {name!r}, {detail!r}),".format(
            addr=hex(image_base + s["address"]), name=s["name"], detail=s["detail"])
        for s in symbols if s["kind"] in ("export", "function", "vm_entry")
    )
    return f'''# Auto-generated by qvm-tool -- applies recovered QVM/TVM symbols in Ghidra.
# Usage:  analyzeHeadless <proj> <name> -import <binary> -postScript apply_qvm_symbols.py
# @category ACE.QVM
from ghidra.program.model.symbol import SourceType

SYMBOLS = [
{rows}
]

fm = currentProgram.getFunctionManager()
st = currentProgram.getSymbolTable()

for addr, name, detail in SYMBOLS:
    a = toAddr(addr)
    try:
        if fm.getFunctionAt(a) is None:
            createFunction(a, name)
        else:
            f = fm.getFunctionAt(a)
            f.setName(name, SourceType.USER_DEFINED)
        st.createLabel(a, name, SourceType.USER_DEFINED)
        setPlateComment(a, detail)
    except Exception as e:
        print("qvm-tool: failed at %s (%s): %s" % (addr, name, e))

print("qvm-tool: applied %d symbols" % len(SYMBOLS))
'''


def to_ida_idc(symbols: list[dict], image_base: int) -> str:
    lines = ["// Auto-generated by qvm-tool", "#include <idc.idc>",
             "static main() {"]
    for s in symbols:
        if s["kind"] not in ("export", "function", "vm_entry"):
            continue
        lines.append(f'  MakeName(0x{image_base + s["address"]:X}, "{s["name"]}");')
        lines.append(f'  MakeComm(0x{image_base + s["address"]:X}, "{s["detail"]}");')
    lines.append("}")
    return "\n".join(lines) + "\n"
